//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnesthesiaMachineConfigurationData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnesthesiaMachineConfigurationData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}AnesthesiaMachineActionData">
 *       &lt;choice>
 *         &lt;element name="ConfigurationFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Configuration" type="{uri:/mil/tatrc/physiology/datamodel}AnesthesiaMachineData"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnesthesiaMachineConfigurationData", propOrder = {
    "configurationFile",
    "configuration"
})
public class AnesthesiaMachineConfigurationData
    extends AnesthesiaMachineActionData
{

    @XmlElement(name = "ConfigurationFile")
    protected String configurationFile;
    @XmlElement(name = "Configuration")
    protected AnesthesiaMachineData configuration;

    /**
     * Gets the value of the configurationFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigurationFile() {
        return configurationFile;
    }

    /**
     * Sets the value of the configurationFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigurationFile(String value) {
        this.configurationFile = value;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link AnesthesiaMachineData }
     *     
     */
    public AnesthesiaMachineData getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnesthesiaMachineData }
     *     
     */
    public void setConfiguration(AnesthesiaMachineData value) {
        this.configuration = value;
    }

}
