//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AppliedTemperatureData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppliedTemperatureData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}ObjectData">
 *       &lt;sequence>
 *         &lt;element name="AppliedTemperature" type="{uri:/mil/tatrc/physiology/datamodel}ScalarTemperatureData" minOccurs="0"/>
 *         &lt;element name="AppliedSurfaceArea" type="{uri:/mil/tatrc/physiology/datamodel}ScalarAreaData" minOccurs="0"/>
 *         &lt;element name="AppliedSurfaceAreaFraction" type="{uri:/mil/tatrc/physiology/datamodel}ScalarFractionData" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="State" type="{uri:/mil/tatrc/physiology/datamodel}enumOnOff" default="On" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppliedTemperatureData", propOrder = {
    "appliedTemperature",
    "appliedSurfaceArea",
    "appliedSurfaceAreaFraction"
})
public class AppliedTemperatureData
    extends ObjectData
{

    @XmlElement(name = "AppliedTemperature")
    protected ScalarTemperatureData appliedTemperature;
    @XmlElement(name = "AppliedSurfaceArea")
    protected ScalarAreaData appliedSurfaceArea;
    @XmlElement(name = "AppliedSurfaceAreaFraction")
    protected ScalarFractionData appliedSurfaceAreaFraction;
    @XmlAttribute(name = "State")
    protected EnumOnOff state;

    /**
     * Gets the value of the appliedTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarTemperatureData }
     *     
     */
    public ScalarTemperatureData getAppliedTemperature() {
        return appliedTemperature;
    }

    /**
     * Sets the value of the appliedTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarTemperatureData }
     *     
     */
    public void setAppliedTemperature(ScalarTemperatureData value) {
        this.appliedTemperature = value;
    }

    /**
     * Gets the value of the appliedSurfaceArea property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarAreaData }
     *     
     */
    public ScalarAreaData getAppliedSurfaceArea() {
        return appliedSurfaceArea;
    }

    /**
     * Sets the value of the appliedSurfaceArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarAreaData }
     *     
     */
    public void setAppliedSurfaceArea(ScalarAreaData value) {
        this.appliedSurfaceArea = value;
    }

    /**
     * Gets the value of the appliedSurfaceAreaFraction property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarFractionData }
     *     
     */
    public ScalarFractionData getAppliedSurfaceAreaFraction() {
        return appliedSurfaceAreaFraction;
    }

    /**
     * Sets the value of the appliedSurfaceAreaFraction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarFractionData }
     *     
     */
    public void setAppliedSurfaceAreaFraction(ScalarFractionData value) {
        this.appliedSurfaceAreaFraction = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link EnumOnOff }
     *     
     */
    public EnumOnOff getState() {
        if (state == null) {
            return EnumOnOff.ON;
        } else {
            return state;
        }
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumOnOff }
     *     
     */
    public void setState(EnumOnOff value) {
        this.state = value;
    }

}
