//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChestCompressionForceScaleData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChestCompressionForceScaleData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}ChestCompressionData">
 *       &lt;sequence>
 *         &lt;element name="ForceScale" type="{uri:/mil/tatrc/physiology/datamodel}ScalarFractionData"/>
 *         &lt;element name="ForcePeriod" type="{uri:/mil/tatrc/physiology/datamodel}ScalarTimeData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChestCompressionForceScaleData", propOrder = {
    "forceScale",
    "forcePeriod"
})
public class ChestCompressionForceScaleData
    extends ChestCompressionData
{

    @XmlElement(name = "ForceScale", required = true)
    protected ScalarFractionData forceScale;
    @XmlElement(name = "ForcePeriod")
    protected ScalarTimeData forcePeriod;

    /**
     * Gets the value of the forceScale property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarFractionData }
     *     
     */
    public ScalarFractionData getForceScale() {
        return forceScale;
    }

    /**
     * Sets the value of the forceScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarFractionData }
     *     
     */
    public void setForceScale(ScalarFractionData value) {
        this.forceScale = value;
    }

    /**
     * Gets the value of the forcePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarTimeData }
     *     
     */
    public ScalarTimeData getForcePeriod() {
        return forcePeriod;
    }

    /**
     * Sets the value of the forcePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarTimeData }
     *     
     */
    public void setForcePeriod(ScalarTimeData value) {
        this.forcePeriod = value;
    }

}
