//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComprehensiveMetabolicPanelData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComprehensiveMetabolicPanelData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}PatientAssessmentData">
 *       &lt;sequence>
 *         &lt;element name="Albumin" type="{uri:/mil/tatrc/physiology/datamodel}ScalarMassPerVolumeData" minOccurs="0"/>
 *         &lt;element name="ALP" type="{uri:/mil/tatrc/physiology/datamodel}ScalarMassPerVolumeData" minOccurs="0"/>
 *         &lt;element name="ALT" type="{uri:/mil/tatrc/physiology/datamodel}ScalarMassPerVolumeData" minOccurs="0"/>
 *         &lt;element name="AST" type="{uri:/mil/tatrc/physiology/datamodel}ScalarMassPerVolumeData" minOccurs="0"/>
 *         &lt;element name="BUN" type="{uri:/mil/tatrc/physiology/datamodel}ScalarMassPerVolumeData" minOccurs="0"/>
 *         &lt;element name="Calcium" type="{uri:/mil/tatrc/physiology/datamodel}ScalarMassPerVolumeData" minOccurs="0"/>
 *         &lt;element name="Chloride" type="{uri:/mil/tatrc/physiology/datamodel}ScalarAmountPerVolumeData" minOccurs="0"/>
 *         &lt;element name="CO2" type="{uri:/mil/tatrc/physiology/datamodel}ScalarAmountPerVolumeData" minOccurs="0"/>
 *         &lt;element name="Creatinine" type="{uri:/mil/tatrc/physiology/datamodel}ScalarMassPerVolumeData" minOccurs="0"/>
 *         &lt;element name="Glucose" type="{uri:/mil/tatrc/physiology/datamodel}ScalarMassPerVolumeData" minOccurs="0"/>
 *         &lt;element name="Potassium" type="{uri:/mil/tatrc/physiology/datamodel}ScalarAmountPerVolumeData" minOccurs="0"/>
 *         &lt;element name="Sodium" type="{uri:/mil/tatrc/physiology/datamodel}ScalarAmountPerVolumeData" minOccurs="0"/>
 *         &lt;element name="TotalBilirubin" type="{uri:/mil/tatrc/physiology/datamodel}ScalarMassPerVolumeData" minOccurs="0"/>
 *         &lt;element name="TotalProtein" type="{uri:/mil/tatrc/physiology/datamodel}ScalarMassPerVolumeData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComprehensiveMetabolicPanelData", propOrder = {
    "albumin",
    "alp",
    "alt",
    "ast",
    "bun",
    "calcium",
    "chloride",
    "co2",
    "creatinine",
    "glucose",
    "potassium",
    "sodium",
    "totalBilirubin",
    "totalProtein"
})
public class ComprehensiveMetabolicPanelData
    extends PatientAssessmentData
{

    @XmlElement(name = "Albumin")
    protected ScalarMassPerVolumeData albumin;
    @XmlElement(name = "ALP")
    protected ScalarMassPerVolumeData alp;
    @XmlElement(name = "ALT")
    protected ScalarMassPerVolumeData alt;
    @XmlElement(name = "AST")
    protected ScalarMassPerVolumeData ast;
    @XmlElement(name = "BUN")
    protected ScalarMassPerVolumeData bun;
    @XmlElement(name = "Calcium")
    protected ScalarMassPerVolumeData calcium;
    @XmlElement(name = "Chloride")
    protected ScalarAmountPerVolumeData chloride;
    @XmlElement(name = "CO2")
    protected ScalarAmountPerVolumeData co2;
    @XmlElement(name = "Creatinine")
    protected ScalarMassPerVolumeData creatinine;
    @XmlElement(name = "Glucose")
    protected ScalarMassPerVolumeData glucose;
    @XmlElement(name = "Potassium")
    protected ScalarAmountPerVolumeData potassium;
    @XmlElement(name = "Sodium")
    protected ScalarAmountPerVolumeData sodium;
    @XmlElement(name = "TotalBilirubin")
    protected ScalarMassPerVolumeData totalBilirubin;
    @XmlElement(name = "TotalProtein")
    protected ScalarMassPerVolumeData totalProtein;

    /**
     * Gets the value of the albumin property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public ScalarMassPerVolumeData getAlbumin() {
        return albumin;
    }

    /**
     * Sets the value of the albumin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public void setAlbumin(ScalarMassPerVolumeData value) {
        this.albumin = value;
    }

    /**
     * Gets the value of the alp property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public ScalarMassPerVolumeData getALP() {
        return alp;
    }

    /**
     * Sets the value of the alp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public void setALP(ScalarMassPerVolumeData value) {
        this.alp = value;
    }

    /**
     * Gets the value of the alt property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public ScalarMassPerVolumeData getALT() {
        return alt;
    }

    /**
     * Sets the value of the alt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public void setALT(ScalarMassPerVolumeData value) {
        this.alt = value;
    }

    /**
     * Gets the value of the ast property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public ScalarMassPerVolumeData getAST() {
        return ast;
    }

    /**
     * Sets the value of the ast property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public void setAST(ScalarMassPerVolumeData value) {
        this.ast = value;
    }

    /**
     * Gets the value of the bun property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public ScalarMassPerVolumeData getBUN() {
        return bun;
    }

    /**
     * Sets the value of the bun property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public void setBUN(ScalarMassPerVolumeData value) {
        this.bun = value;
    }

    /**
     * Gets the value of the calcium property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public ScalarMassPerVolumeData getCalcium() {
        return calcium;
    }

    /**
     * Sets the value of the calcium property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public void setCalcium(ScalarMassPerVolumeData value) {
        this.calcium = value;
    }

    /**
     * Gets the value of the chloride property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarAmountPerVolumeData }
     *     
     */
    public ScalarAmountPerVolumeData getChloride() {
        return chloride;
    }

    /**
     * Sets the value of the chloride property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarAmountPerVolumeData }
     *     
     */
    public void setChloride(ScalarAmountPerVolumeData value) {
        this.chloride = value;
    }

    /**
     * Gets the value of the co2 property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarAmountPerVolumeData }
     *     
     */
    public ScalarAmountPerVolumeData getCO2() {
        return co2;
    }

    /**
     * Sets the value of the co2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarAmountPerVolumeData }
     *     
     */
    public void setCO2(ScalarAmountPerVolumeData value) {
        this.co2 = value;
    }

    /**
     * Gets the value of the creatinine property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public ScalarMassPerVolumeData getCreatinine() {
        return creatinine;
    }

    /**
     * Sets the value of the creatinine property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public void setCreatinine(ScalarMassPerVolumeData value) {
        this.creatinine = value;
    }

    /**
     * Gets the value of the glucose property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public ScalarMassPerVolumeData getGlucose() {
        return glucose;
    }

    /**
     * Sets the value of the glucose property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public void setGlucose(ScalarMassPerVolumeData value) {
        this.glucose = value;
    }

    /**
     * Gets the value of the potassium property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarAmountPerVolumeData }
     *     
     */
    public ScalarAmountPerVolumeData getPotassium() {
        return potassium;
    }

    /**
     * Sets the value of the potassium property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarAmountPerVolumeData }
     *     
     */
    public void setPotassium(ScalarAmountPerVolumeData value) {
        this.potassium = value;
    }

    /**
     * Gets the value of the sodium property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarAmountPerVolumeData }
     *     
     */
    public ScalarAmountPerVolumeData getSodium() {
        return sodium;
    }

    /**
     * Sets the value of the sodium property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarAmountPerVolumeData }
     *     
     */
    public void setSodium(ScalarAmountPerVolumeData value) {
        this.sodium = value;
    }

    /**
     * Gets the value of the totalBilirubin property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public ScalarMassPerVolumeData getTotalBilirubin() {
        return totalBilirubin;
    }

    /**
     * Sets the value of the totalBilirubin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public void setTotalBilirubin(ScalarMassPerVolumeData value) {
        this.totalBilirubin = value;
    }

    /**
     * Gets the value of the totalProtein property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public ScalarMassPerVolumeData getTotalProtein() {
        return totalProtein;
    }

    /**
     * Sets the value of the totalProtein property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarMassPerVolumeData }
     *     
     */
    public void setTotalProtein(ScalarMassPerVolumeData value) {
        this.totalProtein = value;
    }

}
