//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConsumeNutrientsData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsumeNutrientsData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}PatientActionData">
 *       &lt;choice>
 *         &lt;element name="NutritionFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Nutrition" type="{uri:/mil/tatrc/physiology/datamodel}NutritionData"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsumeNutrientsData", propOrder = {
    "nutritionFile",
    "nutrition"
})
public class ConsumeNutrientsData
    extends PatientActionData
{

    @XmlElement(name = "NutritionFile")
    protected String nutritionFile;
    @XmlElement(name = "Nutrition")
    protected NutritionData nutrition;

    /**
     * Gets the value of the nutritionFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNutritionFile() {
        return nutritionFile;
    }

    /**
     * Sets the value of the nutritionFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNutritionFile(String value) {
        this.nutritionFile = value;
    }

    /**
     * Gets the value of the nutrition property.
     * 
     * @return
     *     possible object is
     *     {@link NutritionData }
     *     
     */
    public NutritionData getNutrition() {
        return nutrition;
    }

    /**
     * Sets the value of the nutrition property.
     * 
     * @param value
     *     allowed object is
     *     {@link NutritionData }
     *     
     */
    public void setNutrition(NutritionData value) {
        this.nutrition = value;
    }

}
