//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DrugSystemData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DrugSystemData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}SystemData">
 *       &lt;sequence>
 *         &lt;element name="BronchodilationLevel" type="{uri:/mil/tatrc/physiology/datamodel}ScalarFractionData" minOccurs="0"/>
 *         &lt;element name="HeartRateChange" type="{uri:/mil/tatrc/physiology/datamodel}ScalarFrequencyData" minOccurs="0"/>
 *         &lt;element name="MeanBloodPressureChange" type="{uri:/mil/tatrc/physiology/datamodel}ScalarPressureData" minOccurs="0"/>
 *         &lt;element name="NeuromuscularBlockLevel" type="{uri:/mil/tatrc/physiology/datamodel}ScalarFractionData" minOccurs="0"/>
 *         &lt;element name="PulsePressureChange" type="{uri:/mil/tatrc/physiology/datamodel}ScalarPressureData" minOccurs="0"/>
 *         &lt;element name="PupilState" type="{uri:/mil/tatrc/physiology/datamodel}enumPupilState" minOccurs="0"/>
 *         &lt;element name="RespirationRateChange" type="{uri:/mil/tatrc/physiology/datamodel}ScalarFrequencyData" minOccurs="0"/>
 *         &lt;element name="SedationLevel" type="{uri:/mil/tatrc/physiology/datamodel}ScalarFractionData" minOccurs="0"/>
 *         &lt;element name="TidalVolumeChange" type="{uri:/mil/tatrc/physiology/datamodel}ScalarVolumeData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DrugSystemData", propOrder = {
    "bronchodilationLevel",
    "heartRateChange",
    "meanBloodPressureChange",
    "neuromuscularBlockLevel",
    "pulsePressureChange",
    "pupilState",
    "respirationRateChange",
    "sedationLevel",
    "tidalVolumeChange"
})
public class DrugSystemData
    extends SystemData
{

    @XmlElement(name = "BronchodilationLevel")
    protected ScalarFractionData bronchodilationLevel;
    @XmlElement(name = "HeartRateChange")
    protected ScalarFrequencyData heartRateChange;
    @XmlElement(name = "MeanBloodPressureChange")
    protected ScalarPressureData meanBloodPressureChange;
    @XmlElement(name = "NeuromuscularBlockLevel")
    protected ScalarFractionData neuromuscularBlockLevel;
    @XmlElement(name = "PulsePressureChange")
    protected ScalarPressureData pulsePressureChange;
    @XmlElement(name = "PupilState")
    @XmlSchemaType(name = "string")
    protected EnumPupilState pupilState;
    @XmlElement(name = "RespirationRateChange")
    protected ScalarFrequencyData respirationRateChange;
    @XmlElement(name = "SedationLevel")
    protected ScalarFractionData sedationLevel;
    @XmlElement(name = "TidalVolumeChange")
    protected ScalarVolumeData tidalVolumeChange;

    /**
     * Gets the value of the bronchodilationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarFractionData }
     *     
     */
    public ScalarFractionData getBronchodilationLevel() {
        return bronchodilationLevel;
    }

    /**
     * Sets the value of the bronchodilationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarFractionData }
     *     
     */
    public void setBronchodilationLevel(ScalarFractionData value) {
        this.bronchodilationLevel = value;
    }

    /**
     * Gets the value of the heartRateChange property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarFrequencyData }
     *     
     */
    public ScalarFrequencyData getHeartRateChange() {
        return heartRateChange;
    }

    /**
     * Sets the value of the heartRateChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarFrequencyData }
     *     
     */
    public void setHeartRateChange(ScalarFrequencyData value) {
        this.heartRateChange = value;
    }

    /**
     * Gets the value of the meanBloodPressureChange property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarPressureData }
     *     
     */
    public ScalarPressureData getMeanBloodPressureChange() {
        return meanBloodPressureChange;
    }

    /**
     * Sets the value of the meanBloodPressureChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarPressureData }
     *     
     */
    public void setMeanBloodPressureChange(ScalarPressureData value) {
        this.meanBloodPressureChange = value;
    }

    /**
     * Gets the value of the neuromuscularBlockLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarFractionData }
     *     
     */
    public ScalarFractionData getNeuromuscularBlockLevel() {
        return neuromuscularBlockLevel;
    }

    /**
     * Sets the value of the neuromuscularBlockLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarFractionData }
     *     
     */
    public void setNeuromuscularBlockLevel(ScalarFractionData value) {
        this.neuromuscularBlockLevel = value;
    }

    /**
     * Gets the value of the pulsePressureChange property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarPressureData }
     *     
     */
    public ScalarPressureData getPulsePressureChange() {
        return pulsePressureChange;
    }

    /**
     * Sets the value of the pulsePressureChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarPressureData }
     *     
     */
    public void setPulsePressureChange(ScalarPressureData value) {
        this.pulsePressureChange = value;
    }

    /**
     * Gets the value of the pupilState property.
     * 
     * @return
     *     possible object is
     *     {@link EnumPupilState }
     *     
     */
    public EnumPupilState getPupilState() {
        return pupilState;
    }

    /**
     * Sets the value of the pupilState property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumPupilState }
     *     
     */
    public void setPupilState(EnumPupilState value) {
        this.pupilState = value;
    }

    /**
     * Gets the value of the respirationRateChange property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarFrequencyData }
     *     
     */
    public ScalarFrequencyData getRespirationRateChange() {
        return respirationRateChange;
    }

    /**
     * Sets the value of the respirationRateChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarFrequencyData }
     *     
     */
    public void setRespirationRateChange(ScalarFrequencyData value) {
        this.respirationRateChange = value;
    }

    /**
     * Gets the value of the sedationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarFractionData }
     *     
     */
    public ScalarFractionData getSedationLevel() {
        return sedationLevel;
    }

    /**
     * Sets the value of the sedationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarFractionData }
     *     
     */
    public void setSedationLevel(ScalarFractionData value) {
        this.sedationLevel = value;
    }

    /**
     * Gets the value of the tidalVolumeChange property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarVolumeData }
     *     
     */
    public ScalarVolumeData getTidalVolumeChange() {
        return tidalVolumeChange;
    }

    /**
     * Sets the value of the tidalVolumeChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarVolumeData }
     *     
     */
    public void setTidalVolumeChange(ScalarVolumeData value) {
        this.tidalVolumeChange = value;
    }

}
