//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ElectroCardioGramWaveformData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElectroCardioGramWaveformData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}ObjectData">
 *       &lt;sequence>
 *         &lt;element name="Waveform" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Data" type="{uri:/mil/tatrc/physiology/datamodel}FunctionTimeVsElectricPotentialData"/>
 *                   &lt;element name="TimeStep" type="{uri:/mil/tatrc/physiology/datamodel}ScalarTimeData" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Rhythm" use="required" type="{uri:/mil/tatrc/physiology/datamodel}enumHeartRhythm" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElectroCardioGramWaveformData", propOrder = {
    "waveform"
})
public class ElectroCardioGramWaveformData
    extends ObjectData
{

    @XmlElement(name = "Waveform", required = true)
    protected List<ElectroCardioGramWaveformData.Waveform> waveform;

    /**
     * Gets the value of the waveform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the waveform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWaveform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ElectroCardioGramWaveformData.Waveform }
     * 
     * 
     */
    public List<ElectroCardioGramWaveformData.Waveform> getWaveform() {
        if (waveform == null) {
            waveform = new ArrayList<ElectroCardioGramWaveformData.Waveform>();
        }
        return this.waveform;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Data" type="{uri:/mil/tatrc/physiology/datamodel}FunctionTimeVsElectricPotentialData"/>
     *         &lt;element name="TimeStep" type="{uri:/mil/tatrc/physiology/datamodel}ScalarTimeData" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="Rhythm" use="required" type="{uri:/mil/tatrc/physiology/datamodel}enumHeartRhythm" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "data",
        "timeStep"
    })
    public static class Waveform {

        @XmlElement(name = "Data", required = true)
        protected FunctionTimeVsElectricPotentialData data;
        @XmlElement(name = "TimeStep")
        protected ScalarTimeData timeStep;
        @XmlAttribute(name = "Rhythm", required = true)
        protected EnumHeartRhythm rhythm;

        /**
         * Gets the value of the data property.
         * 
         * @return
         *     possible object is
         *     {@link FunctionTimeVsElectricPotentialData }
         *     
         */
        public FunctionTimeVsElectricPotentialData getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         * 
         * @param value
         *     allowed object is
         *     {@link FunctionTimeVsElectricPotentialData }
         *     
         */
        public void setData(FunctionTimeVsElectricPotentialData value) {
            this.data = value;
        }

        /**
         * Gets the value of the timeStep property.
         * 
         * @return
         *     possible object is
         *     {@link ScalarTimeData }
         *     
         */
        public ScalarTimeData getTimeStep() {
            return timeStep;
        }

        /**
         * Sets the value of the timeStep property.
         * 
         * @param value
         *     allowed object is
         *     {@link ScalarTimeData }
         *     
         */
        public void setTimeStep(ScalarTimeData value) {
            this.timeStep = value;
        }

        /**
         * Gets the value of the rhythm property.
         * 
         * @return
         *     possible object is
         *     {@link EnumHeartRhythm }
         *     
         */
        public EnumHeartRhythm getRhythm() {
            return rhythm;
        }

        /**
         * Sets the value of the rhythm property.
         * 
         * @param value
         *     allowed object is
         *     {@link EnumHeartRhythm }
         *     
         */
        public void setRhythm(EnumHeartRhythm value) {
            this.rhythm = value;
        }

    }

}
