//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EndocrineSystemData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EndocrineSystemData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}SystemData">
 *       &lt;sequence>
 *         &lt;element name="InsulinSynthesisRate" type="{uri:/mil/tatrc/physiology/datamodel}ScalarAmountPerTimeData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EndocrineSystemData", propOrder = {
    "insulinSynthesisRate"
})
public class EndocrineSystemData
    extends SystemData
{

    @XmlElement(name = "InsulinSynthesisRate")
    protected ScalarAmountPerTimeData insulinSynthesisRate;

    /**
     * Gets the value of the insulinSynthesisRate property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarAmountPerTimeData }
     *     
     */
    public ScalarAmountPerTimeData getInsulinSynthesisRate() {
        return insulinSynthesisRate;
    }

    /**
     * Sets the value of the insulinSynthesisRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarAmountPerTimeData }
     *     
     */
    public void setInsulinSynthesisRate(ScalarAmountPerTimeData value) {
        this.insulinSynthesisRate = value;
    }

}
