//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumAnesthesiaMachineOxygenSource.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumAnesthesiaMachineOxygenSource">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Wall"/>
 *     &lt;enumeration value="BottleOne"/>
 *     &lt;enumeration value="BottleTwo"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "enumAnesthesiaMachineOxygenSource")
@XmlEnum
public enum EnumAnesthesiaMachineOxygenSource {

    @XmlEnumValue("Wall")
    WALL("Wall"),
    @XmlEnumValue("BottleOne")
    BOTTLE_ONE("BottleOne"),
    @XmlEnumValue("BottleTwo")
    BOTTLE_TWO("BottleTwo");
    private final String value;

    EnumAnesthesiaMachineOxygenSource(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnumAnesthesiaMachineOxygenSource fromValue(String v) {
        for (EnumAnesthesiaMachineOxygenSource c: EnumAnesthesiaMachineOxygenSource.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
