//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumMicroscopicObservationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumMicroscopicObservationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LowPowerField"/>
 *     &lt;enumeration value="HighPowerField"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "enumMicroscopicObservationType")
@XmlEnum
public enum EnumMicroscopicObservationType {

    @XmlEnumValue("LowPowerField")
    LOW_POWER_FIELD("LowPowerField"),
    @XmlEnumValue("HighPowerField")
    HIGH_POWER_FIELD("HighPowerField");
    private final String value;

    EnumMicroscopicObservationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnumMicroscopicObservationType fromValue(String v) {
        for (EnumMicroscopicObservationType c: EnumMicroscopicObservationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
