//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumAnatomy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumAnatomy">
 *   &lt;restriction base="{uri:/mil/tatrc/physiology/datamodel}enumCompartment">
 *     &lt;enumeration value="Head"/>
 *     &lt;enumeration value="Brain"/>
 *     &lt;enumeration value="Neck"/>
 *     &lt;enumeration value="Esophagus"/>
 *     &lt;enumeration value="Trachea"/>
 *     &lt;enumeration value="Core"/>
 *     &lt;enumeration value="Bone"/>
 *     &lt;enumeration value="Fat"/>
 *     &lt;enumeration value="Muscle"/>
 *     &lt;enumeration value="Pulmonary"/>
 *     &lt;enumeration value="PulmonaryArteries"/>
 *     &lt;enumeration value="PulmonaryCapillaries"/>
 *     &lt;enumeration value="PulmonaryVeins"/>
 *     &lt;enumeration value="PulmonaryShunt"/>
 *     &lt;enumeration value="Lungs"/>
 *     &lt;enumeration value="LeftLung"/>
 *     &lt;enumeration value="LeftDeadSpace"/>
 *     &lt;enumeration value="LeftAlveoli"/>
 *     &lt;enumeration value="LeftPulmonaryArteries"/>
 *     &lt;enumeration value="LeftPulmonaryCapillaries"/>
 *     &lt;enumeration value="LeftPulmonaryVeins"/>
 *     &lt;enumeration value="LeftPulmonaryShunt"/>
 *     &lt;enumeration value="RightLung"/>
 *     &lt;enumeration value="RightDeadSpace"/>
 *     &lt;enumeration value="RightAlveoli"/>
 *     &lt;enumeration value="RightPulmonaryArteries"/>
 *     &lt;enumeration value="RightPulmonaryCapillaries"/>
 *     &lt;enumeration value="RightPulmonaryVeins"/>
 *     &lt;enumeration value="RightPulmonaryShunt"/>
 *     &lt;enumeration value="PleuralCavity"/>
 *     &lt;enumeration value="LeftPleuralCavity"/>
 *     &lt;enumeration value="RightPleuralCavity"/>
 *     &lt;enumeration value="Cardiothoracic"/>
 *     &lt;enumeration value="Aorta"/>
 *     &lt;enumeration value="Heart"/>
 *     &lt;enumeration value="Myocardium"/>
 *     &lt;enumeration value="LeftHeart"/>
 *     &lt;enumeration value="RightHeart"/>
 *     &lt;enumeration value="Pericardium"/>
 *     &lt;enumeration value="VenaCava"/>
 *     &lt;enumeration value="Abdomen"/>
 *     &lt;enumeration value="UpperUrinaryTract"/>
 *     &lt;enumeration value="Kidneys"/>
 *     &lt;enumeration value="LeftKidney"/>
 *     &lt;enumeration value="LeftRenalArtery"/>
 *     &lt;enumeration value="LeftRenalVein"/>
 *     &lt;enumeration value="LeftNephron"/>
 *     &lt;enumeration value="LeftAfferentArteriole"/>
 *     &lt;enumeration value="LeftGlomerularCapillaries"/>
 *     &lt;enumeration value="LeftEfferentArteriole"/>
 *     &lt;enumeration value="LeftPeritubularCapillaries"/>
 *     &lt;enumeration value="LeftBowmansCapsules"/>
 *     &lt;enumeration value="LeftTubules"/>
 *     &lt;enumeration value="LeftUreter"/>
 *     &lt;enumeration value="RightKidney"/>
 *     &lt;enumeration value="RightRenalArtery"/>
 *     &lt;enumeration value="RightRenalVein"/>
 *     &lt;enumeration value="RightNephron"/>
 *     &lt;enumeration value="RightAfferentArteriole"/>
 *     &lt;enumeration value="RightGlomerularCapillaries"/>
 *     &lt;enumeration value="RightEfferentArteriole"/>
 *     &lt;enumeration value="RightPeritubularCapillaries"/>
 *     &lt;enumeration value="RightBowmansCapsules"/>
 *     &lt;enumeration value="RightTubules"/>
 *     &lt;enumeration value="RightUreter"/>
 *     &lt;enumeration value="LowerUrinaryTract"/>
 *     &lt;enumeration value="Urethra"/>
 *     &lt;enumeration value="Bladder"/>
 *     &lt;enumeration value="Gut"/>
 *     &lt;enumeration value="Splanchnic"/>
 *     &lt;enumeration value="SmallIntestine"/>
 *     &lt;enumeration value="LargeIntestine"/>
 *     &lt;enumeration value="Liver"/>
 *     &lt;enumeration value="Spleen"/>
 *     &lt;enumeration value="Stomach"/>
 *     &lt;enumeration value="Periphery"/>
 *     &lt;enumeration value="LeftArm"/>
 *     &lt;enumeration value="LeftLeg"/>
 *     &lt;enumeration value="RightArm"/>
 *     &lt;enumeration value="RightLeg"/>
 *     &lt;enumeration value="Skin"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "enumAnatomy")
@XmlEnum
public enum EnumAnatomy {

    @XmlEnumValue("Head")
    HEAD("Head"),
    @XmlEnumValue("Brain")
    BRAIN("Brain"),
    @XmlEnumValue("Neck")
    NECK("Neck"),
    @XmlEnumValue("Esophagus")
    ESOPHAGUS("Esophagus"),
    @XmlEnumValue("Trachea")
    TRACHEA("Trachea"),
    @XmlEnumValue("Core")
    CORE("Core"),
    @XmlEnumValue("Bone")
    BONE("Bone"),
    @XmlEnumValue("Fat")
    FAT("Fat"),
    @XmlEnumValue("Muscle")
    MUSCLE("Muscle"),
    @XmlEnumValue("Pulmonary")
    PULMONARY("Pulmonary"),
    @XmlEnumValue("PulmonaryArteries")
    PULMONARY_ARTERIES("PulmonaryArteries"),
    @XmlEnumValue("PulmonaryCapillaries")
    PULMONARY_CAPILLARIES("PulmonaryCapillaries"),
    @XmlEnumValue("PulmonaryVeins")
    PULMONARY_VEINS("PulmonaryVeins"),
    @XmlEnumValue("PulmonaryShunt")
    PULMONARY_SHUNT("PulmonaryShunt"),
    @XmlEnumValue("Lungs")
    LUNGS("Lungs"),
    @XmlEnumValue("LeftLung")
    LEFT_LUNG("LeftLung"),
    @XmlEnumValue("LeftDeadSpace")
    LEFT_DEAD_SPACE("LeftDeadSpace"),
    @XmlEnumValue("LeftAlveoli")
    LEFT_ALVEOLI("LeftAlveoli"),
    @XmlEnumValue("LeftPulmonaryArteries")
    LEFT_PULMONARY_ARTERIES("LeftPulmonaryArteries"),
    @XmlEnumValue("LeftPulmonaryCapillaries")
    LEFT_PULMONARY_CAPILLARIES("LeftPulmonaryCapillaries"),
    @XmlEnumValue("LeftPulmonaryVeins")
    LEFT_PULMONARY_VEINS("LeftPulmonaryVeins"),
    @XmlEnumValue("LeftPulmonaryShunt")
    LEFT_PULMONARY_SHUNT("LeftPulmonaryShunt"),
    @XmlEnumValue("RightLung")
    RIGHT_LUNG("RightLung"),
    @XmlEnumValue("RightDeadSpace")
    RIGHT_DEAD_SPACE("RightDeadSpace"),
    @XmlEnumValue("RightAlveoli")
    RIGHT_ALVEOLI("RightAlveoli"),
    @XmlEnumValue("RightPulmonaryArteries")
    RIGHT_PULMONARY_ARTERIES("RightPulmonaryArteries"),
    @XmlEnumValue("RightPulmonaryCapillaries")
    RIGHT_PULMONARY_CAPILLARIES("RightPulmonaryCapillaries"),
    @XmlEnumValue("RightPulmonaryVeins")
    RIGHT_PULMONARY_VEINS("RightPulmonaryVeins"),
    @XmlEnumValue("RightPulmonaryShunt")
    RIGHT_PULMONARY_SHUNT("RightPulmonaryShunt"),
    @XmlEnumValue("PleuralCavity")
    PLEURAL_CAVITY("PleuralCavity"),
    @XmlEnumValue("LeftPleuralCavity")
    LEFT_PLEURAL_CAVITY("LeftPleuralCavity"),
    @XmlEnumValue("RightPleuralCavity")
    RIGHT_PLEURAL_CAVITY("RightPleuralCavity"),
    @XmlEnumValue("Cardiothoracic")
    CARDIOTHORACIC("Cardiothoracic"),
    @XmlEnumValue("Aorta")
    AORTA("Aorta"),
    @XmlEnumValue("Heart")
    HEART("Heart"),
    @XmlEnumValue("Myocardium")
    MYOCARDIUM("Myocardium"),
    @XmlEnumValue("LeftHeart")
    LEFT_HEART("LeftHeart"),
    @XmlEnumValue("RightHeart")
    RIGHT_HEART("RightHeart"),
    @XmlEnumValue("Pericardium")
    PERICARDIUM("Pericardium"),
    @XmlEnumValue("VenaCava")
    VENA_CAVA("VenaCava"),
    @XmlEnumValue("Abdomen")
    ABDOMEN("Abdomen"),
    @XmlEnumValue("UpperUrinaryTract")
    UPPER_URINARY_TRACT("UpperUrinaryTract"),
    @XmlEnumValue("Kidneys")
    KIDNEYS("Kidneys"),
    @XmlEnumValue("LeftKidney")
    LEFT_KIDNEY("LeftKidney"),
    @XmlEnumValue("LeftRenalArtery")
    LEFT_RENAL_ARTERY("LeftRenalArtery"),
    @XmlEnumValue("LeftRenalVein")
    LEFT_RENAL_VEIN("LeftRenalVein"),
    @XmlEnumValue("LeftNephron")
    LEFT_NEPHRON("LeftNephron"),
    @XmlEnumValue("LeftAfferentArteriole")
    LEFT_AFFERENT_ARTERIOLE("LeftAfferentArteriole"),
    @XmlEnumValue("LeftGlomerularCapillaries")
    LEFT_GLOMERULAR_CAPILLARIES("LeftGlomerularCapillaries"),
    @XmlEnumValue("LeftEfferentArteriole")
    LEFT_EFFERENT_ARTERIOLE("LeftEfferentArteriole"),
    @XmlEnumValue("LeftPeritubularCapillaries")
    LEFT_PERITUBULAR_CAPILLARIES("LeftPeritubularCapillaries"),
    @XmlEnumValue("LeftBowmansCapsules")
    LEFT_BOWMANS_CAPSULES("LeftBowmansCapsules"),
    @XmlEnumValue("LeftTubules")
    LEFT_TUBULES("LeftTubules"),
    @XmlEnumValue("LeftUreter")
    LEFT_URETER("LeftUreter"),
    @XmlEnumValue("RightKidney")
    RIGHT_KIDNEY("RightKidney"),
    @XmlEnumValue("RightRenalArtery")
    RIGHT_RENAL_ARTERY("RightRenalArtery"),
    @XmlEnumValue("RightRenalVein")
    RIGHT_RENAL_VEIN("RightRenalVein"),
    @XmlEnumValue("RightNephron")
    RIGHT_NEPHRON("RightNephron"),
    @XmlEnumValue("RightAfferentArteriole")
    RIGHT_AFFERENT_ARTERIOLE("RightAfferentArteriole"),
    @XmlEnumValue("RightGlomerularCapillaries")
    RIGHT_GLOMERULAR_CAPILLARIES("RightGlomerularCapillaries"),
    @XmlEnumValue("RightEfferentArteriole")
    RIGHT_EFFERENT_ARTERIOLE("RightEfferentArteriole"),
    @XmlEnumValue("RightPeritubularCapillaries")
    RIGHT_PERITUBULAR_CAPILLARIES("RightPeritubularCapillaries"),
    @XmlEnumValue("RightBowmansCapsules")
    RIGHT_BOWMANS_CAPSULES("RightBowmansCapsules"),
    @XmlEnumValue("RightTubules")
    RIGHT_TUBULES("RightTubules"),
    @XmlEnumValue("RightUreter")
    RIGHT_URETER("RightUreter"),
    @XmlEnumValue("LowerUrinaryTract")
    LOWER_URINARY_TRACT("LowerUrinaryTract"),
    @XmlEnumValue("Urethra")
    URETHRA("Urethra"),
    @XmlEnumValue("Bladder")
    BLADDER("Bladder"),
    @XmlEnumValue("Gut")
    GUT("Gut"),
    @XmlEnumValue("Splanchnic")
    SPLANCHNIC("Splanchnic"),
    @XmlEnumValue("SmallIntestine")
    SMALL_INTESTINE("SmallIntestine"),
    @XmlEnumValue("LargeIntestine")
    LARGE_INTESTINE("LargeIntestine"),
    @XmlEnumValue("Liver")
    LIVER("Liver"),
    @XmlEnumValue("Spleen")
    SPLEEN("Spleen"),
    @XmlEnumValue("Stomach")
    STOMACH("Stomach"),
    @XmlEnumValue("Periphery")
    PERIPHERY("Periphery"),
    @XmlEnumValue("LeftArm")
    LEFT_ARM("LeftArm"),
    @XmlEnumValue("LeftLeg")
    LEFT_LEG("LeftLeg"),
    @XmlEnumValue("RightArm")
    RIGHT_ARM("RightArm"),
    @XmlEnumValue("RightLeg")
    RIGHT_LEG("RightLeg"),
    @XmlEnumValue("Skin")
    SKIN("Skin");
    private final String value;

    EnumAnatomy(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnumAnatomy fromValue(String v) {
        for (EnumAnatomy c: EnumAnatomy.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
