//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumCircuitModelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumCircuitModelType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NA"/>
 *     &lt;enumeration value="Fluid"/>
 *     &lt;enumeration value="Thermal"/>
 *     &lt;enumeration value="Electrical"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "enumCircuitModelType")
@XmlEnum
public enum EnumCircuitModelType {

    NA("NA"),
    @XmlEnumValue("Fluid")
    FLUID("Fluid"),
    @XmlEnumValue("Thermal")
    THERMAL("Thermal"),
    @XmlEnumValue("Electrical")
    ELECTRICAL("Electrical");
    private final String value;

    EnumCircuitModelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnumCircuitModelType fromValue(String v) {
        for (EnumCircuitModelType c: EnumCircuitModelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
