//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnvironmentChangeData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnvironmentChangeData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}EnvironmentActionData">
 *       &lt;choice>
 *         &lt;element name="ConditionsFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Conditions" type="{uri:/mil/tatrc/physiology/datamodel}EnvironmentalConditionsData"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnvironmentChangeData", propOrder = {
    "conditionsFile",
    "conditions"
})
public class EnvironmentChangeData
    extends EnvironmentActionData
{

    @XmlElement(name = "ConditionsFile")
    protected String conditionsFile;
    @XmlElement(name = "Conditions")
    protected EnvironmentalConditionsData conditions;

    /**
     * Gets the value of the conditionsFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionsFile() {
        return conditionsFile;
    }

    /**
     * Sets the value of the conditionsFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionsFile(String value) {
        this.conditionsFile = value;
    }

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link EnvironmentalConditionsData }
     *     
     */
    public EnvironmentalConditionsData getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnvironmentalConditionsData }
     *     
     */
    public void setConditions(EnvironmentalConditionsData value) {
        this.conditions = value;
    }

}
