//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GasCompartmentSubstanceQuantityData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GasCompartmentSubstanceQuantityData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}CompartmentSubstanceQuantityData">
 *       &lt;sequence>
 *         &lt;element name="PartialPressure" type="{uri:/mil/tatrc/physiology/datamodel}ScalarPressureData" minOccurs="0"/>
 *         &lt;element name="Volume" type="{uri:/mil/tatrc/physiology/datamodel}ScalarVolumeData" minOccurs="0"/>
 *         &lt;element name="VolumeFraction" type="{uri:/mil/tatrc/physiology/datamodel}ScalarFractionData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GasCompartmentSubstanceQuantityData", propOrder = {
    "partialPressure",
    "volume",
    "volumeFraction"
})
public class GasCompartmentSubstanceQuantityData
    extends CompartmentSubstanceQuantityData
{

    @XmlElement(name = "PartialPressure")
    protected ScalarPressureData partialPressure;
    @XmlElement(name = "Volume")
    protected ScalarVolumeData volume;
    @XmlElement(name = "VolumeFraction")
    protected ScalarFractionData volumeFraction;

    /**
     * Gets the value of the partialPressure property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarPressureData }
     *     
     */
    public ScalarPressureData getPartialPressure() {
        return partialPressure;
    }

    /**
     * Sets the value of the partialPressure property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarPressureData }
     *     
     */
    public void setPartialPressure(ScalarPressureData value) {
        this.partialPressure = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarVolumeData }
     *     
     */
    public ScalarVolumeData getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarVolumeData }
     *     
     */
    public void setVolume(ScalarVolumeData value) {
        this.volume = value;
    }

    /**
     * Gets the value of the volumeFraction property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarFractionData }
     *     
     */
    public ScalarFractionData getVolumeFraction() {
        return volumeFraction;
    }

    /**
     * Sets the value of the volumeFraction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarFractionData }
     *     
     */
    public void setVolumeFraction(ScalarFractionData value) {
        this.volumeFraction = value;
    }

}
