//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GastrointestinalSystemData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GastrointestinalSystemData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}SystemData">
 *       &lt;sequence>
 *         &lt;element name="ChymeAbsorbtionRate" type="{uri:/mil/tatrc/physiology/datamodel}ScalarVolumePerTimeData" minOccurs="0"/>
 *         &lt;element name="NutrientsInStomach" type="{uri:/mil/tatrc/physiology/datamodel}NutritionData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GastrointestinalSystemData", propOrder = {
    "chymeAbsorbtionRate",
    "nutrientsInStomach"
})
public class GastrointestinalSystemData
    extends SystemData
{

    @XmlElement(name = "ChymeAbsorbtionRate")
    protected ScalarVolumePerTimeData chymeAbsorbtionRate;
    @XmlElement(name = "NutrientsInStomach")
    protected NutritionData nutrientsInStomach;

    /**
     * Gets the value of the chymeAbsorbtionRate property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarVolumePerTimeData }
     *     
     */
    public ScalarVolumePerTimeData getChymeAbsorbtionRate() {
        return chymeAbsorbtionRate;
    }

    /**
     * Sets the value of the chymeAbsorbtionRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarVolumePerTimeData }
     *     
     */
    public void setChymeAbsorbtionRate(ScalarVolumePerTimeData value) {
        this.chymeAbsorbtionRate = value;
    }

    /**
     * Gets the value of the nutrientsInStomach property.
     * 
     * @return
     *     possible object is
     *     {@link NutritionData }
     *     
     */
    public NutritionData getNutrientsInStomach() {
        return nutrientsInStomach;
    }

    /**
     * Sets the value of the nutrientsInStomach property.
     * 
     * @param value
     *     allowed object is
     *     {@link NutritionData }
     *     
     */
    public void setNutrientsInStomach(NutritionData value) {
        this.nutrientsInStomach = value;
    }

}
