//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LiquidCompartmentData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LiquidCompartmentData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}FluidCompartmentData">
 *       &lt;sequence>
 *         &lt;element name="pH" type="{uri:/mil/tatrc/physiology/datamodel}ScalarData" minOccurs="0"/>
 *         &lt;element name="SubstanceQuantity" type="{uri:/mil/tatrc/physiology/datamodel}LiquidCompartmentSubstanceQuantityData" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LiquidCompartmentData", propOrder = {
    "ph",
    "substanceQuantity"
})
public class LiquidCompartmentData
    extends FluidCompartmentData
{

    @XmlElement(name = "pH")
    protected ScalarData ph;
    @XmlElement(name = "SubstanceQuantity")
    protected List<LiquidCompartmentSubstanceQuantityData> substanceQuantity;

    /**
     * Gets the value of the ph property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarData }
     *     
     */
    public ScalarData getPH() {
        return ph;
    }

    /**
     * Sets the value of the ph property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarData }
     *     
     */
    public void setPH(ScalarData value) {
        this.ph = value;
    }

    /**
     * Gets the value of the substanceQuantity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the substanceQuantity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubstanceQuantity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LiquidCompartmentSubstanceQuantityData }
     * 
     * 
     */
    public List<LiquidCompartmentSubstanceQuantityData> getSubstanceQuantity() {
        if (substanceQuantity == null) {
            substanceQuantity = new ArrayList<LiquidCompartmentSubstanceQuantityData>();
        }
        return this.substanceQuantity;
    }

}
