//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LobarPneumoniaData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LobarPneumoniaData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}PatientConditionData">
 *       &lt;sequence>
 *         &lt;element name="Severity" type="{uri:/mil/tatrc/physiology/datamodel}ScalarFractionData"/>
 *         &lt;element name="LeftLungAffected" type="{uri:/mil/tatrc/physiology/datamodel}ScalarFractionData"/>
 *         &lt;element name="RightLungAffected" type="{uri:/mil/tatrc/physiology/datamodel}ScalarFractionData"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LobarPneumoniaData", propOrder = {
    "severity",
    "leftLungAffected",
    "rightLungAffected"
})
public class LobarPneumoniaData
    extends PatientConditionData
{

    @XmlElement(name = "Severity", required = true)
    protected ScalarFractionData severity;
    @XmlElement(name = "LeftLungAffected", required = true)
    protected ScalarFractionData leftLungAffected;
    @XmlElement(name = "RightLungAffected", required = true)
    protected ScalarFractionData rightLungAffected;

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarFractionData }
     *     
     */
    public ScalarFractionData getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarFractionData }
     *     
     */
    public void setSeverity(ScalarFractionData value) {
        this.severity = value;
    }

    /**
     * Gets the value of the leftLungAffected property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarFractionData }
     *     
     */
    public ScalarFractionData getLeftLungAffected() {
        return leftLungAffected;
    }

    /**
     * Sets the value of the leftLungAffected property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarFractionData }
     *     
     */
    public void setLeftLungAffected(ScalarFractionData value) {
        this.leftLungAffected = value;
    }

    /**
     * Gets the value of the rightLungAffected property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarFractionData }
     *     
     */
    public ScalarFractionData getRightLungAffected() {
        return rightLungAffected;
    }

    /**
     * Sets the value of the rightLungAffected property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarFractionData }
     *     
     */
    public void setRightLungAffected(ScalarFractionData value) {
        this.rightLungAffected = value;
    }

}
