//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OxygenWallPortPressureLossData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OxygenWallPortPressureLossData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}AnesthesiaMachineActionData">
 *       &lt;attribute name="State" type="{uri:/mil/tatrc/physiology/datamodel}enumOnOff" default="On" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OxygenWallPortPressureLossData")
public class OxygenWallPortPressureLossData
    extends AnesthesiaMachineActionData
{

    @XmlAttribute(name = "State")
    protected EnumOnOff state;

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link EnumOnOff }
     *     
     */
    public EnumOnOff getState() {
        if (state == null) {
            return EnumOnOff.ON;
        } else {
            return state;
        }
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumOnOff }
     *     
     */
    public void setState(EnumOnOff value) {
        this.state = value;
    }

}
