//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:16:52 PM EST 
//


package mil.tatrc.physiology.datamodel.bind;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhysiologyEngineDynamicStabilizationData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhysiologyEngineDynamicStabilizationData">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:/mil/tatrc/physiology/datamodel}PhysiologyEngineStabilizationData">
 *       &lt;sequence>
 *         &lt;element name="RestingStabilizationCriteria" type="{uri:/mil/tatrc/physiology/datamodel}PhysiologyEngineDynamicStabilizationCriteriaData"/>
 *         &lt;element name="FeedbackStabilizationCriteria" type="{uri:/mil/tatrc/physiology/datamodel}PhysiologyEngineDynamicStabilizationCriteriaData" minOccurs="0"/>
 *         &lt;element name="ConditionStabilization" type="{uri:/mil/tatrc/physiology/datamodel}PhysiologyEngineDynamicConditionStabilizationData" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysiologyEngineDynamicStabilizationData", propOrder = {
    "restingStabilizationCriteria",
    "feedbackStabilizationCriteria",
    "conditionStabilization"
})
public class PhysiologyEngineDynamicStabilizationData
    extends PhysiologyEngineStabilizationData
{

    @XmlElement(name = "RestingStabilizationCriteria", required = true)
    protected PhysiologyEngineDynamicStabilizationCriteriaData restingStabilizationCriteria;
    @XmlElement(name = "FeedbackStabilizationCriteria")
    protected PhysiologyEngineDynamicStabilizationCriteriaData feedbackStabilizationCriteria;
    @XmlElement(name = "ConditionStabilization")
    protected List<PhysiologyEngineDynamicConditionStabilizationData> conditionStabilization;

    /**
     * Gets the value of the restingStabilizationCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link PhysiologyEngineDynamicStabilizationCriteriaData }
     *     
     */
    public PhysiologyEngineDynamicStabilizationCriteriaData getRestingStabilizationCriteria() {
        return restingStabilizationCriteria;
    }

    /**
     * Sets the value of the restingStabilizationCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysiologyEngineDynamicStabilizationCriteriaData }
     *     
     */
    public void setRestingStabilizationCriteria(PhysiologyEngineDynamicStabilizationCriteriaData value) {
        this.restingStabilizationCriteria = value;
    }

    /**
     * Gets the value of the feedbackStabilizationCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link PhysiologyEngineDynamicStabilizationCriteriaData }
     *     
     */
    public PhysiologyEngineDynamicStabilizationCriteriaData getFeedbackStabilizationCriteria() {
        return feedbackStabilizationCriteria;
    }

    /**
     * Sets the value of the feedbackStabilizationCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysiologyEngineDynamicStabilizationCriteriaData }
     *     
     */
    public void setFeedbackStabilizationCriteria(PhysiologyEngineDynamicStabilizationCriteriaData value) {
        this.feedbackStabilizationCriteria = value;
    }

    /**
     * Gets the value of the conditionStabilization property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conditionStabilization property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConditionStabilization().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysiologyEngineDynamicConditionStabilizationData }
     * 
     * 
     */
    public List<PhysiologyEngineDynamicConditionStabilizationData> getConditionStabilization() {
        if (conditionStabilization == null) {
            conditionStabilization = new ArrayList<PhysiologyEngineDynamicConditionStabilizationData>();
        }
        return this.conditionStabilization;
    }

}
