// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

/**
 * @file
 * @brief Generated from InterCircuitConnectionData.xsd.
 */

#ifndef INTER_CIRCUIT_CONNECTION_DATA_HXX
#define INTER_CIRCUIT_CONNECTION_DATA_HXX

#ifndef XSD_CXX11
#define XSD_CXX11
#endif

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_TREE_USE_CHAR
#define XSD_CXX_TREE_USE_CHAR
#endif

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 4000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include "cdm-schema.hxx"

// Forward declarations.
//
namespace mil
{
  namespace tatrc
  {
    namespace physiology
    {
      namespace datamodel
      {
        class InterCircuitConnectionData;
      }
    }
  }
}


#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include "ObjectData.hxx"

namespace mil
{
  namespace tatrc
  {
    namespace physiology
    {
      /**
       * @brief C++ namespace for the %uri:/mil/tatrc/physiology/datamodel
       * schema namespace.
       */
      namespace datamodel
      {
        /**
         * @brief Class corresponding to the %InterCircuitConnectionData schema type.
         *
         * @nosubgrouping
         */
        class InterCircuitConnectionData: public ::mil::tatrc::physiology::datamodel::ObjectData
        {
          public:
          /**
           * @name SourceCircuit
           *
           * @brief Accessor and modifier functions for the %SourceCircuit
           * required element.
           */
          //@{

          /**
           * @brief Element type.
           */
          typedef ::xml_schema::idref SourceCircuit_type;

          /**
           * @brief Element traits type.
           */
          typedef ::xsd::cxx::tree::traits< SourceCircuit_type, char > SourceCircuit_traits;

          /**
           * @brief Return a read-only (constant) reference to the element.
           *
           * @return A constant reference to the element.
           */
          const SourceCircuit_type&
          SourceCircuit () const;

          /**
           * @brief Return a read-write reference to the element.
           *
           * @return A reference to the element.
           */
          SourceCircuit_type&
          SourceCircuit ();

          /**
           * @brief Set the element value.
           *
           * @param x A new value to set.
           *
           * This function makes a copy of its argument and sets it as
           * the new value of the element.
           */
          void
          SourceCircuit (const SourceCircuit_type& x);

          /**
           * @brief Set the element value without copying.
           *
           * @param p A new value to use.
           *
           * This function will try to use the passed value directly
           * instead of making a copy.
           */
          void
          SourceCircuit (::std::unique_ptr< SourceCircuit_type > p);

          //@}

          /**
           * @name TargetCircuit
           *
           * @brief Accessor and modifier functions for the %TargetCircuit
           * required element.
           */
          //@{

          /**
           * @brief Element type.
           */
          typedef ::xml_schema::idref TargetCircuit_type;

          /**
           * @brief Element traits type.
           */
          typedef ::xsd::cxx::tree::traits< TargetCircuit_type, char > TargetCircuit_traits;

          /**
           * @brief Return a read-only (constant) reference to the element.
           *
           * @return A constant reference to the element.
           */
          const TargetCircuit_type&
          TargetCircuit () const;

          /**
           * @brief Return a read-write reference to the element.
           *
           * @return A reference to the element.
           */
          TargetCircuit_type&
          TargetCircuit ();

          /**
           * @brief Set the element value.
           *
           * @param x A new value to set.
           *
           * This function makes a copy of its argument and sets it as
           * the new value of the element.
           */
          void
          TargetCircuit (const TargetCircuit_type& x);

          /**
           * @brief Set the element value without copying.
           *
           * @param p A new value to use.
           *
           * This function will try to use the passed value directly
           * instead of making a copy.
           */
          void
          TargetCircuit (::std::unique_ptr< TargetCircuit_type > p);

          //@}

          /**
           * @name SourceCircuitNode
           *
           * @brief Accessor and modifier functions for the %SourceCircuitNode
           * required element.
           */
          //@{

          /**
           * @brief Element type.
           */
          typedef ::xml_schema::idref SourceCircuitNode_type;

          /**
           * @brief Element traits type.
           */
          typedef ::xsd::cxx::tree::traits< SourceCircuitNode_type, char > SourceCircuitNode_traits;

          /**
           * @brief Return a read-only (constant) reference to the element.
           *
           * @return A constant reference to the element.
           */
          const SourceCircuitNode_type&
          SourceCircuitNode () const;

          /**
           * @brief Return a read-write reference to the element.
           *
           * @return A reference to the element.
           */
          SourceCircuitNode_type&
          SourceCircuitNode ();

          /**
           * @brief Set the element value.
           *
           * @param x A new value to set.
           *
           * This function makes a copy of its argument and sets it as
           * the new value of the element.
           */
          void
          SourceCircuitNode (const SourceCircuitNode_type& x);

          /**
           * @brief Set the element value without copying.
           *
           * @param p A new value to use.
           *
           * This function will try to use the passed value directly
           * instead of making a copy.
           */
          void
          SourceCircuitNode (::std::unique_ptr< SourceCircuitNode_type > p);

          //@}

          /**
           * @name TargetCircuitNode
           *
           * @brief Accessor and modifier functions for the %TargetCircuitNode
           * required element.
           */
          //@{

          /**
           * @brief Element type.
           */
          typedef ::xml_schema::idref TargetCircuitNode_type;

          /**
           * @brief Element traits type.
           */
          typedef ::xsd::cxx::tree::traits< TargetCircuitNode_type, char > TargetCircuitNode_traits;

          /**
           * @brief Return a read-only (constant) reference to the element.
           *
           * @return A constant reference to the element.
           */
          const TargetCircuitNode_type&
          TargetCircuitNode () const;

          /**
           * @brief Return a read-write reference to the element.
           *
           * @return A reference to the element.
           */
          TargetCircuitNode_type&
          TargetCircuitNode ();

          /**
           * @brief Set the element value.
           *
           * @param x A new value to set.
           *
           * This function makes a copy of its argument and sets it as
           * the new value of the element.
           */
          void
          TargetCircuitNode (const TargetCircuitNode_type& x);

          /**
           * @brief Set the element value without copying.
           *
           * @param p A new value to use.
           *
           * This function will try to use the passed value directly
           * instead of making a copy.
           */
          void
          TargetCircuitNode (::std::unique_ptr< TargetCircuitNode_type > p);

          //@}

          /**
           * @name Path
           *
           * @brief Accessor and modifier functions for the %Path
           * required element.
           */
          //@{

          /**
           * @brief Element type.
           */
          typedef ::xml_schema::idref Path_type;

          /**
           * @brief Element traits type.
           */
          typedef ::xsd::cxx::tree::traits< Path_type, char > Path_traits;

          /**
           * @brief Return a read-only (constant) reference to the element.
           *
           * @return A constant reference to the element.
           */
          const Path_type&
          Path () const;

          /**
           * @brief Return a read-write reference to the element.
           *
           * @return A reference to the element.
           */
          Path_type&
          Path ();

          /**
           * @brief Set the element value.
           *
           * @param x A new value to set.
           *
           * This function makes a copy of its argument and sets it as
           * the new value of the element.
           */
          void
          Path (const Path_type& x);

          /**
           * @brief Set the element value without copying.
           *
           * @param p A new value to use.
           *
           * This function will try to use the passed value directly
           * instead of making a copy.
           */
          void
          Path (::std::unique_ptr< Path_type > p);

          //@}

          /**
           * @name Constructors
           */
          //@{

          /**
           * @brief Default constructor.
           *
           * Note that this constructor leaves required elements and
           * attributes uninitialized.
           */
          InterCircuitConnectionData ();

          /**
           * @brief Create an instance from the ultimate base and
           * initializers for required elements and attributes.
           */
          InterCircuitConnectionData (const SourceCircuit_type&,
                                      const TargetCircuit_type&,
                                      const SourceCircuitNode_type&,
                                      const TargetCircuitNode_type&,
                                      const Path_type&);

          /**
           * @brief Create an instance from the ultimate base and
           * initializers for required elements and attributes
           * (::std::unique_ptr version).
           *
           * This constructor will try to use the passed values directly
           * instead of making copies.
           */
          InterCircuitConnectionData (::std::unique_ptr< SourceCircuit_type >,
                                      ::std::unique_ptr< TargetCircuit_type >,
                                      ::std::unique_ptr< SourceCircuitNode_type >,
                                      ::std::unique_ptr< TargetCircuitNode_type >,
                                      ::std::unique_ptr< Path_type >);

          /**
           * @brief Create an instance from a DOM element.
           *
           * @param e A DOM element to extract the data from.
           * @param f Flags to create the new instance with.
           * @param c A pointer to the object that will contain the new
           * instance.
           */
          InterCircuitConnectionData (const ::xercesc::DOMElement& e,
                                      ::xml_schema::flags f = 0,
                                      ::xml_schema::container* c = 0);

          /**
           * @brief Copy constructor.
           *
           * @param x An instance to make a copy of.
           * @param f Flags to create the copy with.
           * @param c A pointer to the object that will contain the copy.
           *
           * For polymorphic object models use the @c _clone function instead.
           */
          InterCircuitConnectionData (const InterCircuitConnectionData& x,
                                      ::xml_schema::flags f = 0,
                                      ::xml_schema::container* c = 0);

          /**
           * @brief Copy the instance polymorphically.
           *
           * @param f Flags to create the copy with.
           * @param c A pointer to the object that will contain the copy.
           * @return A pointer to the dynamically allocated copy.
           *
           * This function ensures that the dynamic type of the instance is
           * used for copying and should be used for polymorphic object
           * models instead of the copy constructor.
           */
          virtual InterCircuitConnectionData*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          /**
           * @brief Copy assignment operator.
           *
           * @param x An instance to make a copy of.
           * @return A reference to itself.
           *
           * For polymorphic object models use the @c _clone function instead.
           */
          InterCircuitConnectionData&
          operator= (const InterCircuitConnectionData& x);

          //@}

          /**
           * @brief Destructor.
           */
          virtual 
          ~InterCircuitConnectionData ();

          // Implementation.
          //

          //@cond

          protected:
          void
          parse (::xsd::cxx::xml::dom::parser< char >&,
                 ::xml_schema::flags);

          protected:
          ::xsd::cxx::tree::one< SourceCircuit_type > SourceCircuit_;
          ::xsd::cxx::tree::one< TargetCircuit_type > TargetCircuit_;
          ::xsd::cxx::tree::one< SourceCircuitNode_type > SourceCircuitNode_;
          ::xsd::cxx::tree::one< TargetCircuitNode_type > TargetCircuitNode_;
          ::xsd::cxx::tree::one< Path_type > Path_;

          //@endcond
        };
      }
    }
  }
}

#include <iosfwd>

namespace mil
{
  namespace tatrc
  {
    namespace physiology
    {
      namespace datamodel
      {
        ::std::ostream&
        operator<< (::std::ostream&, const InterCircuitConnectionData&);
      }
    }
  }
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace mil
{
  namespace tatrc
  {
    namespace physiology
    {
      namespace datamodel
      {
      }
    }
  }
}

#include <iosfwd>

#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>
#include <xercesc/framework/XMLFormatter.hpp>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

namespace mil
{
  namespace tatrc
  {
    namespace physiology
    {
      namespace datamodel
      {
        void
        operator<< (::xercesc::DOMElement&, const InterCircuitConnectionData&);
      }
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
#include "decimal.hxx"

#include "double-parsing.hxx"
#include "decimal-parsing.hxx"

#include "double-serialization.hxx"
#include "decimal-serialization.hxx"
//
// End epilogue.

#endif // INTER_CIRCUIT_CONNECTION_DATA_HXX
